pull_request_rules:
- name: automatic merge by dependabot
  conditions:
    - status-success=continuous-integration/travis-ci/pr
    - status-success=WIP
    - "#changes-requested-reviews-by=0"
    - base=master
    - label=dependencies
    - author=dependabot[bot]
    - author=dependabot-preview[bot]
    - author=dependabot
  actions:
    merge:
      method: merge
      strict: true
    delete_head_branch: